services:
  proxy:
    build: ./proxy/
    ports:
      - "8000:80"
    networks:
      internal_nw:
        ipv4_address: 172.28.0.2
    depends_on:
      - frontend

  movies:
    build: ./movies/
    environment:
      - DB_USERNAME=admin
      - DB_PASSWORD=adminadmin
      - MSV_PORT=8082
    networks:
      internal_nw:
        ipv4_address: 172.28.0.3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.28.0.3:8082/api/movies"]
      interval: 10s
      timeout: 10s
      retries: 5

  directors:
    build: ./directors/
    environment:
      - DB_USERNAME=admin
      - DB_PASSWORD=adminadmin
      - MSV_PORT=8081
      - MOVIES_API_ENDPOINT=http://172.28.0.3:8082/api/
    networks:
      internal_nw:
        ipv4_address: 172.28.0.4
    depends_on:
      movies:
        condition: service_healthy

  gateway:
    build: ./gateway/
    environment:
      - MSV_PORT=8080
      - HOST_ADDRESS=172.28.0.5
      - MOVIES_ADDRESS=172.28.0.3:8082
      - DIRECTORS_ADDRESS=172.28.0.4:8081
    networks:
      internal_nw:
        ipv4_address: 172.28.0.5
    depends_on:
      - directors

  frontend:
    build: ./website/
    networks:
      internal_nw:
        ipv4_address: 172.28.0.6
    depends_on:
      - gateway

networks:
  internal_nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16